# The "bullseye" flavor of the official docker Python image is based on Debian and includes only necessary packages.
FROM nvidia/cuda:11.4.0-cudnn8-runtime-ubuntu20.04
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update &&\
    apt-get install -y curl python3.9-dev python3.9-distutils
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.9 get-pip.py

# Create the working directory
RUN mkdir /repo
WORKDIR /repo

# Install Python dependencies
COPY requirements.txt ./requirements.txt
RUN sed -i 's/opencv-python/opencv-python-headless/' requirements.txt
RUN sed -i 's/onnxruntime~=1.10.0/onnxruntime-gpu/' requirements.txt
RUN pip install -U pip
RUN pip install -r requirements.txt

# Copy only the relevant directories and files
COPY ocr_inference/ ./ocr_inference
COPY api/ ./api

# Run the web server
EXPOSE 5000
ENV PYTHONPATH ./
ENV OV_EXEC_PROVIDER TensorrtExecutionProvider;CUDAExecutionProvider
CMD python3.9 ./api/app.py
