# The "bullseye" flavor of the official docker Python image is based on Debian and includes only necessary packages.
FROM python:3.9-slim

# Create the working directory
RUN mkdir /repo
WORKDIR /repo

# Install Python dependencies
COPY requirements.txt ./requirements.txt
RUN sed -i 's/opencv-python/opencv-python-headless/' requirements.txt
RUN sed -i 's/onnxruntime~=1.10.0/onnxruntime-openvino/' requirements.txt
RUN pip install -U pip
# RUN pip install openvino==2021.4.2
RUN pip install -r requirements.txt

# Copy only the relevant directories and files
COPY ocr_inference/ ./ocr_inference
COPY api/ ./api

# Run the web server
EXPOSE 5000
ENV PYTHONPATH ./
ENV OV_EXEC_PROVIDER OpenVINOExecutionProvider
CMD python3 ./api/app.py
